name: Trigger auto deployment for agentrag

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/agentrag-AutoDeployTrigger-3289d6b3-e384-473c-bf29-89c7dc01ceb0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AGENTRAG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AGENTRAG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AGENTRAG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: myapprag.azurecr.io
          registryUsername: ${{ secrets.AGENTRAG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AGENTRAG_REGISTRY_PASSWORD }}
          containerAppName: agentrag
          resourceGroup: test_dev
          imageToBuild: myapprag.azurecr.io/agentrag:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


